omegaModel = out.model.Data;

paramText = sprintf([ ...
    'Motor Parameters\n' ...
    'B   = %.4e\n' ...
    'Eff = %.5f\n' ...
    'J   = %.4e\n' ...
    'K_e = %.5f'], ...
    motor_B, motor_Eff, motor_J, motor_Ke);

plot(Time,Raw_data) ; hold on
plot(Time, omegaModel, 'LineWidth', 2) ; 
legend('Raw Omega', 'Omega Model');

xlabel('Time (s)')
ylabel('Omega (rad/s)')

grid on

tb = annotation('textbox', ...
           'String', paramText, ...
           'FitBoxToText', 'on', ...
           'BackgroundColor', 'white', ...
           'EdgeColor', [0.3 0.3 0.3], ...
           'FontSize', 11, ...
           'FontName', 'Consolas');

tb.Units = 'normalized';
tb.Position(1) = 1 - tb.Position(3) - 0.1;  % เว้นขอบขวา
tb.Position(2) = 1 - tb.Position(4) - 0.3;  % เว้นขอบบน